# Generated by Django 2.2.7 on 2021-02-02 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=255, verbose_name='اسم المركز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مركز الحلقة',
                'verbose_name_plural': ' مراكز الحلقات ',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم ')),
                ('email', models.CharField(max_length=150, verbose_name=' الأيمايل')),
                ('feedback', models.TextField(verbose_name='الموضوع')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255, verbose_name='اسم الحلقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الحلقة',
                'verbose_name_plural': ' الحلقات ',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('ikama_number', models.CharField(max_length=200, unique=True, verbose_name=' رقم الهوية / الأقامة')),
                ('surname', models.CharField(max_length=200, verbose_name='اللقب')),
                ('firstname', models.CharField(max_length=200, verbose_name='الاسم ')),
                ('other_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الأب')),
                ('sex', models.CharField(choices=[('1', 'طلاب'), ('2', ' طالبات')], default='1', max_length=10, verbose_name='شطر الطلاب / الطالبات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name=' المستخدم الخاص بالأستاذ ')),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Centers', verbose_name='نوع الحلقة ')),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': ' الأساتذة ',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=10)),
                ('ikama_number', models.CharField(max_length=20, unique=True, verbose_name=' رقم الهوية / الأقامة')),
                ('firstname', models.CharField(max_length=20, verbose_name='الاسم ')),
                ('surname', models.CharField(max_length=20, verbose_name='اللقب')),
                ('other_name', models.CharField(blank=True, max_length=20, verbose_name='اسم الأب')),
                ('sex', models.CharField(choices=[('1', 'طلاب'), ('2', ' طالبات')], default='1', max_length=10, verbose_name='شطر الطلاب / الطالبات')),
                ('date_of_birth', models.PositiveIntegerField(blank=True, null=True, verbose_name=' العمر ')),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now, verbose_name=' تاريخ الإنظمام')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic', verbose_name='الصورة')),
                ('mobile_number', models.CharField(blank=True, max_length=13, verbose_name='جوال الطالب')),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, verbose_name='جوال الأب')),
                ('address', models.TextField(blank=True, max_length=100, verbose_name='العنوان ')),
                ('others', models.TextField(blank=True, max_length=10, verbose_name=' معلومات اخرى')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name=' المستخدم الخاص بالطالب ')),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Centers', verbose_name=' المركز ')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Courses', verbose_name='نوع الحلقة ')),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Staffs', verbose_name=' شيخ الحلقة ')),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': ' الطلاب ',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_type', models.CharField(blank=True, choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=10, null=True)),
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط')], default='active', max_length=10)),
                ('ikama_number', models.CharField(max_length=20, unique=True, verbose_name=' رقم الهوية / الأقامة')),
                ('firstname', models.CharField(blank=True, max_length=20, verbose_name='الاسم ')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='اللقب')),
                ('other_name', models.CharField(blank=True, max_length=20, verbose_name='اسم الأب')),
                ('sex', models.CharField(choices=[('1', 'طلاب'), ('2', ' طالبات')], default='1', max_length=10, verbose_name='شطر الطلاب / الطالبات')),
                ('date_of_birth', models.PositiveIntegerField(blank=True, null=True, verbose_name=' العمر ')),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now, verbose_name=' تاريخ الإنظمام')),
                ('mobile_number', models.CharField(blank=True, max_length=13, verbose_name='جوال الطالب')),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, verbose_name='جوال الأب')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='العنوان ')),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Centers', verbose_name=' المركز ')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Courses', verbose_name='نوع الحلقة ')),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Staffs', verbose_name=' شيخ الحلقة ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': ' الطلاب ',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='التاريخ  ')),
                ('status', models.CharField(blank=True, choices=[('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز'), ('غير حافظ', 'غير حافظ'), ('غائب', 'غائب')], max_length=10, null=True, verbose_name='درجة الحفظ ')),
                ('status2', models.CharField(blank=True, choices=[('جيد', 'جيد'), ('جيد جدا', 'جيد جدا'), ('ممتاز', 'ممتاز'), ('غير حافظ', 'غير حافظ'), ('غائب', 'غائب')], max_length=10, null=True, verbose_name='درجة المراجعة ')),
                ('attendance_date', models.DateField(auto_now=True, verbose_name='التاريخ ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='HalakaApp.Students', verbose_name=' الطالب ')),
            ],
            options={
                'verbose_name': 'التقييم',
                'verbose_name_plural': ' التقييمات ',
                'ordering': ['-attendance_date'],
            },
        ),
    ]
