# Generated by Django 2.2.7 on 2021-02-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HalakaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
