# Generated by Django 2.2.7 on 2021-02-03 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HalakaApp', '0002_auto_20210202_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='user_type',
            field=models.CharField(blank=True, choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name=' المستخدم الخاص بالطالب '),
        ),
    ]
