# Generated by Django 2.2.7 on 2021-02-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HalakaApp', '0003_auto_20210203_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
