# Generated by Django 2.2.7 on 2021-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HalakaApp', '0004_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='others',
        ),
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='العنوان '),
        ),
    ]
