# Generated by Django 3.1.5 on 2021-02-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HalakaApp', '0006_auto_20210203_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='user_type',
        ),
    ]
